### ISSUE TITLE
how did you get the program code ?

### ISSUE THREAD

**Issue by minanagehsalalma** [dilap54/RouterScan-console#1]

**Comment by dilap54** [comment]
LibRouter.pas and rsscan.dpr from [here](http://msk1.stascorp.com/routerscan/prerelease.7z) (src/demoapp/)
liblibrouter.so from [here](https://t.me/routerscan)

**Comment by minanagehsalalma** [comment]
> LibRouter.pas and rsscan.dpr from [here](http://msk1.stascorp.com/routerscan/prerelease.7z) (src/demoapp/)

but this a windows .exe files how did you run them on linux ?



> liblibrouter.so from [here](https://t.me/routerscan)

and this link didn't view a download button !
were you able to add new features ? or add support to new routers ?

**Comment by dilap54** [comment]
> but this a windows .exe files how did you run them on linux ?

The archive contains examples of working with the routerscan library. They are written in delphi and can be compiled on linux using freepascal.
But there is no routerscan library for linux in the archive, only librouter.dll. Fresh libary for linux can be found in telegram chat @routerscan, use the search for attached files (name of file: liblibrouter.so)

> were you able to add new features ? or add support to new routers ?

No, I don't have access to the source code of the routerscan library. You can contact the creator in telegram - [x86corez](https://t.me/x86corez) or [routerscan chat](https://t.me/routerscan)

**Comment by minanagehsalalma** [comment]
@dilap54  i have already contacted him in https://forum.antichat.ru/
but he seems stopped to add updates or new  routers to the program !!


> They are written in delphi and can be compiled on linux using freepascal

this the first time i read about delphi !!
can you explain more how did you  "compiled on linux using freepascal"  ?

**Comment by minanagehsalalma** [comment]
![image](https://user-images.githubusercontent.com/20546638/60137274-ab8caf80-97a6-11e9-9df9-4e7779d534a2.png)
the router scan link gave me this !!

**Comment by binarymaster** [comment]
> can you explain more how did you "compiled on linux using freepascal" ?

Stop spamming here and use the Google.

**Comment by minanagehsalalma** [comment]
@binarymaster  unfortunately google doesn't provide such so specified answers !

**Comment by SwordWorth** [comment]
how to compile the program? I can not compile the code on linux

root@aiclub:~/software/RouterScan-console# fpc rsscan.dpr
Free Pascal Compiler version 3.0.4 [2017/10/03] for x86_64
Copyright (c) 1993-2017 by Florian Klaempfl and others
Target OS: Linux for x86-64
Compiling rsscan.dpr
rsscan.dpr(13,2) Note: APPTYPE is not supported by the target OS
Compiling LibRouter.pas
LibRouter.pas(19,3) Fatal: Can't find unit LCLIntf used by LibRouter
Fatal: Compilation aborted
Error: /usr/bin/ppcx64 returned an error exitcode

**Comment by dilap54** [comment]
I have removed delphi dependency, no more freepascal needed
