### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa6f07968]

### ISSUE THREAD

**Issue by stalkerned** [dilap54/RouterScan-console#2]
После запуска RouterScan мне выдаёт эту ошибку:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa6f07968]

goroutine 19 [running]:
os.(*Process).signal(0x0, 0xa6fbf010, 0xa7048ca8, 0x0, 0x0)
        /data/data/com.termux/files/usr/lib/go/src/os/exec_unix.go:56 +0x24
os.(*Process).Signal(...)
        /data/data/com.termux/files/usr/lib/go/src/os/exec.go:131
os.(*Process).kill(...)
        /data/data/com.termux/files/usr/lib/go/src/os/exec_posix.go:59
os.(*Process).Kill(...)
        /data/data/com.termux/files/usr/lib/go/src/os/exec.go:116
main.rsscanCheck()
        /data/data/com.termux/files/home/go/src/github.com/dilap54/RouterScan-console/routerscan.go:158 +0x135c
created by main.main
        /data/data/com.termux/files/home/go/src/github.com/dilap54/RouterScan-console/routerscan.go:168 +0x98
exit status 2
Помогите решить, если можно

**Comment by dilap54** [comment]
Я переписал routerscan-console, теперь этой ошибки точно нет. Но возможно теперь есть другие :)
