### ISSUE TITLE
RouterScan 

### ISSUE THREAD

**Issue by cvvmusic** [dilap54/RouterScan-console#3]
А вам вот не кажется, что нужно было сделать на основе nmap? Чтобы программа сама определяла порты, а то нужно указывать от 80, от 1024 до 65565. А это означает, что RouterScan перебирает все порты на 1 ip около 3-5 минут... Додумайте решение через nmap, чтобы программа не перебирала порты.

**Comment by dilap54** [comment]
Поиск открытых портов не является основной функцией программы. Эффективней сначала с помощью nmap (а еще круче zmap) подготавливать список ip адресов с открытыми портами, а потом отправлять его в routerscan.
